name: Vochtopoigrat CI
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  init:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install

      - name: lint test
        run: npm run lint:fix

      - name: unit test
        run: npm run test
